### ISSUE TITLE
Remove call to `logging.basicConfig()' 

### ISSUE THREAD

**Issue by MathiasLorenz** [energyquantified/eq-python-client#104]
In [/api/events on line 50](https://github.com/energyquantified/eq-python-client/blob/9ec83cc603f1e55e2cd42208feb92b580bfa037e/energyquantified/api/events.py#L50C8-L50C8) you call `logging.basicConfig()', which makes it impossible for any user of your package to call that method afterwards. Quoting the [logging documentation](https://docs.python.org/3/howto/logging.html#logging-to-a-file):

> The call to basicConfig() should come before any calls to debug(), info(), etc. Otherwise, those functions will call basicConfig() for you with the default options. As it’s intended as a one-off simple configuration facility, only the first call will actually do anything: subsequent calls are effectively no-ops.

This means that my call to `basicConfig()` is, as the documentation says, a no op.

Simply commenting out line 50 in your package when I run locally fixes the issue and I can do `basicConfig()` without issues. And on line 51 in the same file, you ensure you are using a package-local logger, which is exactly what you're supposed to do (without the line beforehand)! I am not super strong on the Python specifics for logging in libraries, but as far as I understand, you can attach a handler to that logger defined in line 51 to achieve the same result (without impacting downstream consumers of your library 😉).

Another way to fix the issue as a user (for anyone else interested) is to remove the handler on the root logger which you have initialised and create your own (without using `basicConfig` because, as we have seen, all subsequent calls are no ops), like

```
.. imports (including energyquantified)

logger = logging.getLogger('root')
logger.handlers.clear()

ch = logging.StreamHandler()
logger.setLevel("INFO")
ch.setFormatter(logging.Formatter("%(asctime)s.%(msecs)04d %(levelname)-8s %(message)s"))
logger.addHandler(ch)

.. your code
```

**Comment by fredriksvendsen** [comment]
Thank you for pointing out this bug, @MathiasLorenz.

Fixed in `v0.13.1`: https://github.com/energyquantified/eq-python-client/releases/tag/v0.13.1
