### ISSUE TITLE
Customize User Agent for Monitoring

### ISSUE THREAD

**Issue by komape** [energyquantified/eq-python-client#107]
The HTTP Header User Agent can be used to "identify the application, operating system, vendor, and/or version of the requesting user agent". See further documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

We should make use of that by setting the HTTP header of requests made by the EQ Python Client to `eq-python-client/0.13.1` (for the current version).

This helps us monitor requests and identify those made through the python client.

**Comment by jonmd** [comment]
It's already in there:

https://github.com/energyquantified/eq-python-client/blob/master/energyquantified/http/session.py#L13
https://github.com/energyquantified/eq-python-client/blob/master/energyquantified/http/session.py#L50

However, we could change the format to better reflect the `<product>/<version>` scheme.
