### ISSUE TITLE
Error when fetching currency data with default CET timezone

### ISSUE THREAD

**Issue by chrjx** [energyquantified/eq-python-client#117]
Hi, 

I tried to fetch currency data with time series api as following: 

```
currency_data = EQ.timeseries.load(   
    "Currency EUR/GBP ECB D Forex", 
    begin=date(2024, 9, 17),
    end=date(2024, 10, 8),
    frequency=Frequency.P1D,
    time_zone=CET
)
```

Even though the CET is the default time zone for currency data, it still throws the error: 

```
Field="timezone", message: Timezone conversion is not allowed for the frequency P1D
```

**Comment by fredriksvendsen** [comment]
Hello @chrjx 

This is a server-side issue. I have fixed this in our API, and the change will be deployed early next week.
