### ISSUE TITLE
Border class __repr__ error

### ISSUE THREAD

**Issue by stanton119** [energyquantified/eq-python-client#32]
Hi,

I can't print the border objects

Example:
```
from energyquantified.metadata import Area
areas = Area.by_tag('GB')
borders = areas.borders
print(borders)
```

Error:
```
energyquantified\metadata\area.py in __repr__(self)
     277             self.sink.tag,
     278             # self.allocations,
 --> 279             sorted(self.allocations),
     280         )
     281  
TypeError: '<' not supported between instances of 'Allocation' and 'Allocation'
```

Looks like the `Allocation` class doesnt have the dunder methods for less than (`__lt__`) and greater than (`__gt__`) and therefore cannot run the sorting.

Running on version 0.6
Python 3.8.10

**Comment by jonmd** [comment]
I've published a fix in **v0.6.1**

Thanks for the bug report, @stanton119. I didn't notice that you posted an issue until today – can't remember getting a notification. Sorry about the delay.
