### ISSUE TITLE
Add Unit Parameter

### ISSUE THREAD

**Issue by komape** [energyquantified/eq-python-client#66]
Following the implementation of unit conversion via an API parameter (see https://github.com/energyquantified/core/issues/232), the new parameter must be added to this SDK.

- [x] Include parameter in response

**Comment by komape** [comment]
How many checks of the parameters should be done on the clients side before sending a request? For instance, should the SDK check the `unit` parameter if it is used in combination with a frequency lower than P1D?

**Comment by jonmd** [comment]
> @jonmd How many checks of the parameters should be done on the clients side before sending a request? For instance, should the SDK check the `unit` parameter if it is used in combination with a frequency lower than P1D?

@komape 

We only do simple and straightforward checks client-side. So no need for full validations.

I can't think of any restrictions on units related to frequency, or am I wrong?

**Comment by komape** [comment]
@jonmd The frequency limitation only applies for currency conversions. But as I understand your comment, we do not check this within the Python SDK>
