### ISSUE TITLE
Remove limitation for relative instances

### ISSUE THREAD

**Issue by fredriksvendsen** [energyquantified/eq-python-client#90]
```python
def relative(
            self,
            curve,
            begin=None,
            end=None,
            tag=None,
            days_ahead=1,
            issued="latest",
            time_of_day=None,
            after_time_of_day=None,
            before_time_of_day=None,
            time_zone=None,
            frequency=None,
            aggregation=None,
            hour_filter=None,
            threshold=None,
            unit=None):
        # ...
        # Additional validation checks
        if sum(1 if t is not None else 0 for t in
               (time_of_day, after_time_of_day, before_time_of_day)) > 1:
            raise ValidationError(reason=(
                "At most one of the following fields must be set: "
                "time_of_day, after_time_of_day, before_time_of_day"
            ))
```

Is it necessary to also require one of `time_of_day`, `after_time_of_day` or `before_time_of_day` to be set, considering `issued` (`earliest` / `latest`) is required?

I think it makes sense to have `time_of_day`, `after_time_of_day` and `before_time_of_day` as optional.

**Comment by komape** [comment]
All three are optional, and not required. The validation ensures that only one of them is set, and not both or all three of them. Nevertheless, it is also valid to set none of them. Is that what you mean?

Surprisingly we don't have this limitation on the backend side. Should we add it?

**Comment by fredriksvendsen** [comment]
@komape 
> All three are optional, and not required. The validation ensures that only one of them is set, and not both or all three of them. Nevertheless, it is also valid to set none of them. Is that what you mean?

Yea, I misread it as `if not sum(..) > 1` and did not even double check. My bad.

> Surprisingly we don't have this limitation on the backend side. Should we add it?

Sure, you can create an issue and add it to the next cool down. Low prio.

**Comment by komape** [comment]
> > Surprisingly we don't have this limitation on the backend side. Should we add it?
> 
> Sure, you can create an issue and add it to the next cool down. Low prio.

The question is if we need to limit or if we can live without it?
